version: "3.7"
services:
  website:
    build: .
    image: blog-website
    container_name: blog-website
    labels:
      - "PROJECT=blog"
      - "STATUS=docker"
    networks:
      - blog-network
    ports:
      - "3000:3000"
    environment:
      - API_ENTRY=$API_ENTRY
      - NODE_ENV=development
      - START_COMMAND=dev

networks:
  blog-network:
    labels:
      - "PROJECT=blog"
      - "STATUS=docker"
    name: blog-network