version: "3.7"
services:
  website:
    build: .
    image: blog-website
    container_name: blog-website
    labels:
      - "PROJECT=blog"
      - "SERVICE=website"
    networks:
      - blog-network
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - START_COMMAND=start
      - API_ENTRY=https://blog-server

networks:
  blog-network:
    name: blog-network
    labels:
      - "PROJECT=blog"
      - "SERVICE=website"
